# Generated by Django 2.1.7 on 2019-03-10 10:23

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tasks',
            name='assignee',
        ),
        migrations.AddField(
            model_name='tasks',
            name='assignee',
            field=models.ManyToManyField(related_name='task_assignee', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='teams',
            name='users',
            field=models.ManyToManyField(related_name='team_user', to=settings.AUTH_USER_MODEL),
        ),
    ]
