# Generated by Django 2.1.7 on 2019-03-10 10:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20190310_1603'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comments',
            name='author',
        ),
        migrations.RemoveField(
            model_name='comments',
            name='task',
        ),
        migrations.RemoveField(
            model_name='tasks',
            name='assignee',
        ),
        migrations.RemoveField(
            model_name='tasks',
            name='owner',
        ),
        migrations.RemoveField(
            model_name='teams',
            name='owner',
        ),
        migrations.RemoveField(
            model_name='teams',
            name='users',
        ),
        migrations.DeleteModel(
            name='Comments',
        ),
        migrations.DeleteModel(
            name='Tasks',
        ),
        migrations.DeleteModel(
            name='Teams',
        ),
    ]
