# Generated by Django 2.1.7 on 2019-03-10 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_auto_20190310_1610'),
    ]

    operations = [
        migrations.AddField(
            model_name='tasks',
            name='name',
            field=models.CharField(default=1, max_length=20),
            preserve_default=False,
        ),
    ]
