# Generated by Django 2.1.7 on 2019-03-10 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_tasks_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='tasks',
            name='name_url',
            field=models.CharField(default=1, max_length=30),
            preserve_default=False,
        ),
    ]
