# Generated by Django 2.1.7 on 2019-03-10 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_tasks_name_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tasks',
            name='name_url',
        ),
        migrations.AddField(
            model_name='teams',
            name='name_url',
            field=models.CharField(default=1, max_length=30),
            preserve_default=False,
        ),
    ]
