# Generated by Django 2.1.7 on 2019-03-10 15:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_auto_20190310_2016'),
    ]

    operations = [
        migrations.AddField(
            model_name='tasks',
            name='team',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='team', to='core.Teams'),
            preserve_default=False,
        ),
    ]
