# Generated by Django 2.1.7 on 2019-03-10 19:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_auto_20190310_2140'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tasks',
            name='team',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='team', to='core.Teams'),
        ),
    ]
