# Generated by Django 2.1.7 on 2019-03-10 19:59

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_auto_20190311_0035'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comments',
            name='created_date',
        ),
        migrations.AddField(
            model_name='comments',
            name='last_modified',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2019, 3, 11, 1, 29, 24, 838316)),
        ),
        migrations.AlterField(
            model_name='tasks',
            name='last_modified',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2019, 3, 11, 1, 29, 24, 836317)),
        ),
    ]
