# Generated by Django 2.1.7 on 2019-03-10 20:00

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_auto_20190311_0129'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comments',
            name='last_modified',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2019, 3, 11, 1, 30, 50, 805139)),
        ),
        migrations.AlterField(
            model_name='tasks',
            name='last_modified',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2019, 3, 11, 1, 30, 50, 804140)),
        ),
    ]
