# Generated by Django 2.1.7 on 2019-03-11 13:19

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_auto_20190311_0130'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comments',
            name='last_modified',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2019, 3, 11, 18, 49, 18, 225353)),
        ),
        migrations.AlterField(
            model_name='tasks',
            name='last_modified',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2019, 3, 11, 18, 49, 18, 223354)),
        ),
        migrations.AlterField(
            model_name='tasks',
            name='name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='tasks',
            name='status',
            field=models.CharField(choices=[('planned', 'Planned'), ('in_progress', 'In Progress'), ('done', 'Done')], default='planned', max_length=30),
        ),
        migrations.AlterField(
            model_name='teams',
            name='name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='teams',
            name='name_url',
            field=models.CharField(max_length=100),
        ),
    ]
