# Generated by Django 2.1.7 on 2019-03-16 11:12

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_auto_20190311_1849'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teams',
            name='name_url',
        ),
        migrations.AlterField(
            model_name='comments',
            name='last_modified',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2019, 3, 16, 16, 42, 26, 727864)),
        ),
        migrations.AlterField(
            model_name='tasks',
            name='last_modified',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2019, 3, 16, 16, 42, 26, 726865)),
        ),
    ]
